// Infinite.Unfold.swift
// Full anamorphism with separate state and element types.

extension Infinite {
    /// An infinite sequence generated by unfolding a state through a step function.
    ///
    /// `Unfold` is the general anamorphism—the categorical dual of fold (catamorphism).
    /// Given an initial state and a step function that produces an element and next state,
    /// it generates an infinite sequence.
    ///
    /// ## Example
    ///
    /// ```swift
    /// // Fibonacci sequence using pair state
    /// let fib = Infinite.Unfold(seed: (0, 1)) { (a, b) in
    ///     (a, (b, a + b))  // emit a, next state is (b, a+b)
    /// }
    /// print(Array(fib.prefix(10))) // [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
    ///
    /// // Natural numbers with explicit state
    /// let naturals = Infinite.Unfold(seed: 0) { n in (n, n + 1) }
    /// print(Array(naturals.prefix(5))) // [0, 1, 2, 3, 4]
    /// ```
    ///
    /// ## Mathematical Interpretation
    ///
    /// `Unfold` implements the anamorphism:
    /// ```
    /// ana : (S → A × S) → S → Stream A
    /// ana(step)(s) = let (a, s') = step(s) in a : ana(step)(s')
    /// ```
    ///
    /// This is the universal morphism from a coalgebra `(S, step: S → A × S)` to
    /// the final coalgebra of streams.
    ///
    /// ## Comparison to Iterate
    ///
    /// - `Iterate`: State = Element, simpler API for endomorphisms
    /// - `Unfold`: Separate State and Element types, full generality
    ///
    /// Use `Iterate` when `f: A → A` suffices. Use `Unfold` when you need
    /// hidden state (e.g., Fibonacci needs pair state but emits single values).
    public struct Unfold<State, Element> {
        /// The current state of the unfold.
        @usableFromInline
        let seed: State

        /// The step function producing an element and next state.
        @usableFromInline
        let step: @Sendable (State) -> (Element, State)

        /// Creates an infinite sequence by unfolding from a seed state.
        ///
        /// - Parameters:
        ///   - seed: The initial state.
        ///   - step: A function that takes the current state and returns
        ///           a tuple of (emitted element, next state).
        @inlinable
        public init(seed: State, step: @escaping @Sendable (State) -> (Element, State)) {
            self.seed = seed
            self.step = step
        }
    }
}

// MARK: - Sendable

extension Infinite.Unfold: Sendable where State: Sendable {}

// MARK: - Observable

extension Infinite.Unfold: Infinite.Observable {
    /// The element produced from the current state.
    @inlinable
    public var head: Element {
        step(seed).0
    }

    /// The sequence continuing from the next state.
    @inlinable
    public var tail: Self {
        Infinite.Unfold(seed: step(seed).1, step: step)
    }
}

// MARK: - Enumerable
//
// Sequence conformance is provided via Observable: Enumerable: Sequence.
// Iterator is Infinite.Observable.Iterator (see Infinite.Observable.Iterator.swift).
