// Infinite.Iterate.swift
// Repeated function application: x, f(x), f(f(x)), ...

extension Infinite {
    /// An infinite sequence generated by repeated function application.
    ///
    /// `Iterate` produces `x, f(x), f(f(x)), f(f(f(x))), ...` by repeatedly
    /// applying a transformation to an initial value.
    ///
    /// ## Example
    ///
    /// ```swift
    /// // Natural numbers: 0, 1, 2, 3, ...
    /// let naturals = Infinite.Iterate(initial: 0) { $0 + 1 }
    /// print(Array(naturals.prefix(5))) // [0, 1, 2, 3, 4]
    ///
    /// // Powers of 2: 1, 2, 4, 8, 16, ...
    /// let powers = Infinite.Iterate(initial: 1) { $0 * 2 }
    /// print(Array(powers.prefix(5))) // [1, 2, 4, 8, 16]
    /// ```
    ///
    /// ## Mathematical Interpretation
    ///
    /// `Iterate(x, f)` corresponds to the corecursive definition:
    /// ```
    /// iterate(x, f) = x : iterate(f(x), f)
    /// ```
    ///
    /// This is the unique anamorphism from the coalgebra `(x, f)` to streams,
    /// where the state is the current value and the step applies `f`.
    ///
    /// ## Comparison to Unfold
    ///
    /// `Iterate` is a special case of `Unfold` where:
    /// - State type equals Element type
    /// - Step function `f` produces `(f(s), f(s))` — same value for output and next state
    ///
    /// Use `Iterate` when your generator is a simple endomorphism (same type in/out).
    /// Use `Unfold` when you need separate state from output values.
    public struct Iterate<Element> {
        /// The current value in the iteration.
        @usableFromInline
        let initial: Element

        /// The transformation applied at each step.
        @usableFromInline
        let transform: @Sendable (Element) -> Element

        /// Creates an infinite iteration sequence.
        ///
        /// - Parameters:
        ///   - initial: The first element of the sequence.
        ///   - transform: The function applied repeatedly to generate subsequent elements.
        @inlinable
        public init(initial: Element, _ transform: @escaping @Sendable (Element) -> Element) {
            self.initial = initial
            self.transform = transform
        }
    }
}

// MARK: - Sendable

extension Infinite.Iterate: Sendable where Element: Sendable {}

// MARK: - Observable

extension Infinite.Iterate: Infinite.Observable {
    /// The current element.
    @inlinable
    public var head: Element { initial }

    /// The sequence starting from `f(head)`.
    @inlinable
    public var tail: Self {
        Infinite.Iterate(initial: transform(initial), transform)
    }
}

// MARK: - Enumerable
//
// Sequence conformance is provided via Observable: Enumerable: Sequence.
// Iterator is Infinite.Observable.Iterator (see Infinite.Observable.Iterator.swift).
